// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Switchyard.InventoryAPI.Data;

#nullable disable

namespace Switchyard.InventoryAPI.Data.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Switchyard.Domain.Clothing", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PriceEffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Projected")
                        .HasColumnType("boolean");

                    b.Property<string>("RowKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SKUMarker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UnloadedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey");

                    b.ToTable("Clothing", (string)null);
                });

            modelBuilder.Entity("Switchyard.Domain.PPE", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PriceEffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Projected")
                        .HasColumnType("boolean");

                    b.Property<string>("RowKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SKUMarker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UnloadedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey");

                    b.ToTable("PPE", (string)null);
                });

            modelBuilder.Entity("Switchyard.Domain.Tool", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PriceEffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Projected")
                        .HasColumnType("boolean");

                    b.Property<string>("RowKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SKUMarker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UnloadedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey");

                    b.ToTable("Tools", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
